CREATE OR REPLACE WAREHOUSE PRJ10_WH
WITH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE
INITIALLY_SUSPENDED=FALSE;

CREATE OR REPLACE DATABASE PRJ10;

CREATE OR REPLACE SCHEMA PRJ10.CUSTOMER_ANALYTICS;

USE WAREHOUSE PRJ10_WH;
USE DATABASE PRJ10;
USE SCHEMA CUSTOMER_ANALYTICS;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE='CSV'
FIELD_DELIMITER=','
SKIP_HEADER=1
NULL_IF=('NULL','null','')
FIELD_OPTIONALLY_ENCLOSED_BY='"';

CREATE STAGE CUSTOMER_STAGE
FILE_FORMAT=CSV_FORMAT;

LIST @CUSTOMER_STAGE;

CREATE OR REPLACE TABLE STG_CUSTOMERS_INITIALL(CUSTOMER_ID NUMBER,CUSTOMER_NAME VARCHAR(100),
CITY VARCHAR(100),STATE VARCHAR(100),MEMBERSHIP VARCHAR(50),SEGMENT VARCHAR(50));

CREATE OR REPLACE TABLE STG_CUSTOMERS_UPDATE(CUSTOMER_ID NUMBER,CUTOMER_NAME VARCHAR(100),
CITY VARCHAR(100),STATE VARCHAR(100),MEMBERSHIP VARCHAR(50),SEGMENT VARCHAR(50),EFFECTIVE_DATE DATE);

COPY INTO STG_CUSTOMERS_INITIALL
FROM @CUSTOMER_STAGE/customers_initial10.csv
FILE_FORMAT=CSV_FORMAT;

COPY INTO STG_CUSTOMERS_UPDATE
FROM @CUSTOMER_STAGE/customer_updates10.csv;

CREATE TABLE DIM_CUSTOMER_TYPE3(CUSTOMER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
CUSTOMER_ID NUMBER,
CUSTOMER_NAME VARCHAR(100),CITY VARCHAR(100),
STATE VARCHAR(100),CURRENT_MEMBERSHIP VARCHAR(50),PREVIOUS_MEMBERSHIP VARCHAR(50),
SEGMENT VARCHAR(50));

INSERT INTO DIM_CUSTOMER_TYPE3(CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,CURRENT_MEMBERSHIP,PREVIOUS_MEMBERSHIP,SEGMENT)
SELECT CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,MEMBERSHIP AS CURRENT_MEMBERSHIP,NULL AS PREVIOUS_MEMBERSHIP,SEGMENT FROM 
STG_CUSTOMERS_INITIALL;

SELECT * FROM DIM_CUSTOMER_TYPE3 ORDER BY CUSTOMER_ID;

MERGE INT DIM_CUSTOMER_TYPE3 TGT USING STG_CUSTOMERS_UPDATE SRC
ON TGT.CUSTOMER_ID=SRC.CUSTOMER_ID WHEN MATCHED AND TGT.CURRENT_MEMBERSHIP

